name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      ENDPOINT_SUFFIX: ${{ secrets.ENDPOINT_SUFFIX }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - run: pip install tox
      - run: make lint
      # - run: make api-test
      # - name: Run API in container
      #   run: |
      #     make container-api-build
      #     make container-api-run
      #     make container-api-stop
      #     make container-api-delete
      # - name: Run APP in container
      #   run: |
      #     make container-app-build
      #     make container-app-run
      #     make container-app-stop
      #     make container-app-delete
      # - run: make ci
      #   env:
      #     GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
      #     NYTIMES_API_KEY: ${{ secrets.NYTIMES_API_KEY }}
