name: CI

on: [push, pull_request]

jobs:
  commit:
    runs-on: ubuntu-latest
    env:
      AZURE_STORAGE_ACCOUNT: ${{ secrets.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_KEY: ${{ secrets.AZURE_STORAGE_KEY }}
      ENDPOINT_SUFFIX: ${{ secrets.ENDPOINT_SUFFIX }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Upgrade python-pip
        run: python -m pip install --upgrade pip
      - run: pip install tox
      - run: make lint
      - run: make api-test
      - run: |
          make container-build
          make container-run
          docker ps -q | xargs -L 1 docker logs
          make container-stop
          make container-delete
      # - run: make ci
      #   env:
      #     GUARDIAN_API_KEY: ${{ secrets.GUARDIAN_API_KEY }}
      #     NYTIMES_API_KEY: ${{ secrets.NYTIMES_API_KEY }}
